// Generated by CoffeeScript 1.6.3
(function() {
  var addUIElements, awsKey, awsSecret, create_lock, delayed, generateExpiry, generateSignedURL, generated_tag, loadOptions;

  awsKey = null;

  awsSecret = null;

  generated_tag = null;

  create_lock = false;

  loadOptions = function() {
    chrome.storage.local.get('AWSAccessKey', function(data) {
      return awsKey = data.AWSAccessKey;
    });
    return chrome.storage.local.get('AWSAccessSecret', function(data) {
      return awsSecret = data.AWSAccessSecret;
    });
  };

  $(function() {
    loadOptions();
    $(document).bind('DOMSubtreeModified', function() {
      if ($('table', '#properties-panel-properties').length > 0 && $('#properties-panel-property-signed-url').length < 1) {
        addUIElements();
      }
      if ($('#properties-panel-property-signed-url').length === 1 && $('#properties-panel-property-url').is(':visible')) {
        $('#properties-panel-property-signed-url').show();
      }
      if ($('.properties-panel-property-value', '#properties-panel-property-etag').text() !== generated_tag && generated_tag !== null) {
        addUIElements();
        return generated_tag = null;
      }
    });
    return $('#properties-panel-property-url').bind('change', addUIElements());
  });

  delayed = function(time, fkt) {
    return window.setTimeout(fkt, time);
  };

  generateSignedURL = function() {
    var expiry, lnk, origin_link, prefix, resource, sign_src, signature, url, url_sig;
    lnk = $('<a>');
    origin_link = $('.properties-panel-property-value a', '#properties-panel-property-url').attr('href');
    resource = '/' + origin_link.split('/').slice(3).join('/');
    prefix = origin_link.split('/').slice(0, 3).join('/');
    expiry = generateExpiry($(this).data('seconds'));
    sign_src = "GET\n\n\n" + expiry + "\n" + resource;
    signature = CryptoJS.enc.Base64.stringify(CryptoJS.HmacSHA1(sign_src, awsSecret));
    url_sig = encodeURIComponent(signature);
    url = "" + prefix + resource + "?Expires=" + expiry + "&AWSAccessKeyId=" + awsKey + "&Signature=" + url_sig;
    lnk.attr({
      href: url
    });
    lnk.text(url);
    $(this).parent().empty().append(lnk);
    return generated_tag = $('.properties-panel-property-value', '#properties-panel-property-etag').text();
  };

  generateExpiry = function(ttl) {
    var dateObj, now;
    if (ttl == null) {
      ttl = 86400;
    }
    dateObj = new Date;
    now = dateObj.getTime();
    return parseInt(now / 1000) + ttl;
  };

  addUIElements = function() {
    var duration, link, name, ne, seconds, value, _ref;
    if (create_lock) {
      return;
    }
    create_lock = true;
    $('#properties-panel-property-signed-url').remove();
    ne = $('<tr>');
    ne.attr({
      id: 'properties-panel-property-signed-url'
    });
    name = $('<td>');
    name.addClass('properties-panel-property-name');
    name.text('Signed URL:');
    name.appendTo(ne);
    value = $('<td>');
    value.addClass('properties-panel-property-value');
    value.append('Expiry: ');
    _ref = {
      '1h': 3600,
      '1d': 86400,
      '1w': 604800,
      '1m': 2592000,
      '1a': 31536000
    };
    for (duration in _ref) {
      seconds = _ref[duration];
      link = $('<a>');
      link.attr({
        href: 'javascript:void(0)'
      });
      link.text("" + duration);
      link.data({
        seconds: seconds
      });
      link.bind('click', generateSignedURL);
      link.appendTo(value);
      value.append(' ');
    }
    value.appendTo(ne);
    ne.appendTo($('table', '#properties-panel-properties'));
    return create_lock = false;
  };

}).call(this);
