// Generated by CoffeeScript 1.6.3
(function() {
  var delayed, loadOptions, saveOptions;

  $(function() {
    loadOoptions();
    return $('#save').bind('click', saveOptions);
  });

  delayed = function(time, fkt) {
    return window.setTimeout(fkt, time);
  };

  loadOptions = function() {
    chrome.storage.local.get('AWSAccessKey', function(data) {
      return $('#access_key').val(data.AWSAccessKey);
    });
    return chrome.storage.local.get('AWSAccessSecret', function(data) {
      return $('#secret_key').val(data.AWSAccessSecret);
    });
  };

  saveOptions = function() {
    chrome.storage.local.set({
      'AWSAccessKey': $('#access_key').val(),
      'AWSAccessSecret': $('#secret_key').val()
    });
    $('#status').text('Saved.');
    return delayed(750, function() {
      return $('#status').text('');
    });
  };

}).call(this);
